__all__ = ('PyrestoException','PyrestoInvalidOperationException',
           'PyrestoServerResponseException','PyrestoInvalidRestMethodException',
           'PyrestoInvalidAuthTypeException', )


class PyrestoException(Exception):
    """Base error class for pyresto."""


class PyrestoInvalidOperationException(PyrestoException):
    """Invalid operation error class for Pyresto."""


class PyrestoServerResponseException(PyrestoException):
    """Server response error class for pyresto."""


class PyrestoInvalidRestMethodException(PyrestoException, ValueError):
    """A valid HTTP method is required to make a request."""


class PyrestoInvalidAuthTypeException(PyrestoException, ValueError):
    """
    Error class for exceptions thrown when an invalid auth type is used with
    the global authentication function generated by :func:`enable_auth`
    """
